export var POSTS = [
  {
    slug: "migrar-a-la-nube-2026",
    category: "Digital",
    title: "Como saber si tu empresa necesita migrar a la nube en 2026",
    date: "2026-06-01",
    excerpt: "Tres senales claras de que tu infraestructura on-premise te esta costando mas de lo que crees.",
    body: [
      "Muchas empresas peruanas siguen operando con servidores fisicos que fueron suficientes hace cinco anos, pero que hoy generan costos ocultos: mantenimiento reactivo, falta de escalabilidad y riesgo de caida ante picos de demanda.",
      "Una senal clara es cuando el area de TI dedica mas tiempo a mantener la infraestructura encendida que a mejorar procesos de negocio. Otra es cuando escalar significa comprar hardware nuevo en vez de ajustar un plan de consumo.",
      "La migracion no siempre implica mover todo a la nube. Un modelo hibrido, con cargas criticas en infraestructura propia y cargas variables en AWS o Azure, suele ser el punto de partida mas realista para una pyme o mediana empresa en Peru.",
      "Antes de migrar, recomendamos una auditoria FinOps: entender cuanto cuesta realmente cada carga de trabajo hoy, para no replicar ineficiencias en la nube.",
    ],
  },
  {
    slug: "ley-29733-errores-comunes",
    category: "Compliance",
    title: "Ley 29733: 5 errores comunes en la proteccion de datos personales",
    date: "2026-05-15",
    excerpt: "Estos son los descuidos mas frecuentes que exponen a las empresas peruanas a sanciones de la ANPD.",
    body: [
      "1. No registrar el banco de datos personales ante la Autoridad Nacional de Proteccion de Datos Personales (ANPD), incluso cuando la empresa ya recolecta datos de clientes o empleados de forma habitual.",
      "2. Formularios de consentimiento genericos que no especifican la finalidad real del tratamiento de los datos, lo cual puede invalidar el consentimiento obtenido.",
      "3. Falta de un procedimiento documentado para atender solicitudes de acceso, rectificacion o eliminacion de datos por parte de los titulares.",
      "4. Compartir datos con proveedores externos, como servicios de nube o marketing, sin un contrato de encargo de tratamiento que delimite responsabilidades.",
      "5. No contar con medidas de seguridad tecnicas minimas, como cifrado o control de accesos, sobre las bases de datos que contienen informacion personal.",
      "Una adecuacion tecnica y legal correcta no solo evita multas: reduce el riesgo reputacional frente a un incidente de seguridad.",
    ],
  },
  {
    slug: "mantenimiento-preventivo-sala-servidores",
    category: "Infraestructura",
    title: "Por que el mantenimiento preventivo de tu sala de servidores te ahorra dinero",
    date: "2026-04-22",
    excerpt: "El costo de una falla de climatizacion no planificada suele superar por mucho el costo del mantenimiento anual.",
    body: [
      "Una sala de servidores opera en un rango de temperatura y humedad muy especifico. Cuando el sistema HVAC de precision falla sin aviso previo, el riesgo no es solo el equipo de climatizacion: es la disponibilidad de toda la operacion que depende de esos servidores.",
      "El mantenimiento preventivo programado, que incluye revision de filtros, niveles de refrigerante y calibracion de sensores, cuesta una fraccion de lo que implica una parada de emergencia, sin contar el tiempo de inactividad del negocio.",
      "Recomendamos ademas monitoreo remoto en tiempo real de temperatura y humedad, con alertas automaticas antes de que una desviacion se convierta en una falla critica.",
    ],
  },
  {
    slug: "rpa-vs-ia-generativa",
    category: "Digital",
    title: "RPA vs IA generativa: cual necesita tu empresa",
    date: "2026-03-10",
    excerpt: "No son lo mismo, y usar la herramienta equivocada puede costarte mas tiempo del que ahorra.",
    body: [
      "RPA, o automatizacion robotica de procesos, es ideal para tareas repetitivas y basadas en reglas claras: copiar datos entre sistemas, generar reportes periodicos, validar formularios.",
      "La IA generativa, en cambio, es util cuando la tarea requiere interpretar lenguaje natural o contenido no estructurado: responder consultas de clientes, resumir documentos extensos, clasificar correos por intencion.",
      "Muchas empresas cometen el error de intentar resolver todo con IA generativa cuando un bot RPA simple habria sido mas rapido de implementar y mas barato de mantener. El diagnostico correcto empieza por mapear el proceso, no por elegir la tecnologia primero.",
    ],
  },
  {
    slug: "checklist-ciberseguridad-pymes",
    category: "Compliance",
    title: "Checklist basico de ciberseguridad para pymes peruanas",
    date: "2026-02-18",
    excerpt: "Ocho controles minimos que toda empresa deberia tener, sin importar su tamano.",
    body: [
      "Autenticacion de dos factores en correo corporativo y sistemas criticos.",
      "Copias de respaldo automaticas, con al menos una copia fuera de la red principal.",
      "Actualizaciones de seguridad aplicadas de forma regular en servidores y equipos de trabajo.",
      "Politica de contrasenas minimas y gestor de contrasenas para el equipo.",
      "Capacitacion basica contra phishing para todo el personal, no solo para TI.",
      "Segmentacion de red para separar sistemas criticos de la red general de oficina.",
      "Plan de respuesta a incidentes documentado, aunque sea en una pagina.",
      "Revision periodica de accesos: quien tiene permisos sobre que sistemas, y por que.",
    ],
  },
];
